apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: personal
spec:
  ports:
  - name: 9093-tcp
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: 9094-tcp
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
