apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: alertmanager
spec:
  serviceName: "alertmanager"
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/probe: "true"
    spec:
      containers:
      - name: alertmanager
        image: kuldeepghogre/alertmanager 
        ports:
        - containerPort: 9093
          name: web
        - containerPort: 9094
          name: cluster
