apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: "prometheus"
  replicas: 2 
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: prometheus
        image: kuldeepghogre/prometheus 
        volumeMounts:
        - name: prometheus
          mountPath: /var/app/data
        ports:
        - containerPort: 9090
          name: web
  volumeClaimTemplates:
  - metadata:
      name: prometheus
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi